name: Release

on:
  push:
    branches: ["master"]

concurrency: production

jobs:
  push_to_registry:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: pbgh/ytdlui
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: version=${{ github.sha }}
  deploy_to_kotti:
    name: Deploy to Kotti
    runs-on: ubuntu-latest
    needs: push_to_registry
    environment: production
    steps:
      - name: Deploy using redeployster
        run: |
          curl \
            --silent \
            --show-error \
            -XPOST \
            -H'Authorization: Bearer ${{ secrets.REDEPLOYSTER_TOKEN }}' \
            -D headers.txt \
            https://r10r.s10a.dev/ytdlui
          grep -iq '^Exit-Code: 0\b' headers.txt
